# Generated manually for GIKIASS complete project
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name='Department', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('code', models.CharField(max_length=20, unique=True)), ('full_name', models.CharField(max_length=200))]),
        migrations.CreateModel(name='UploadSession', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('uploaded_file', models.FileField(upload_to='uploads/')), ('uploaded_at', models.DateTimeField(auto_now_add=True)), ('status', models.CharField(choices=[('pending','Pending'),('parsed','Parsed'),('generated','Generated'),('failed','Failed')], default='pending', max_length=20)), ('error_message', models.TextField(blank=True))]),
        migrations.CreateModel(name='Room', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('code', models.CharField(max_length=50, unique=True)), ('capacity', models.PositiveIntegerField(default=60)), ('room_type', models.CharField(choices=[('lecture','Lecture Hall'),('lab','Laboratory')], default='lecture', max_length=10)), ('building', models.CharField(blank=True, max_length=100)), ('is_active', models.BooleanField(default=True))]),
        migrations.CreateModel(name='TimeSlot', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('day', models.CharField(choices=[('MON','Monday'),('TUE','Tuesday'),('WED','Wednesday'),('THU','Thursday'),('FRI','Friday')], max_length=3)), ('period_number', models.PositiveIntegerField()), ('start_time', models.TimeField()), ('end_time', models.TimeField())], options={'ordering': ['day', 'period_number'], 'unique_together': {('day', 'period_number')}}),
        migrations.CreateModel(name='Program', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('code', models.CharField(max_length=20, unique=True)), ('full_name', models.CharField(max_length=200)), ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='api.department'))]),
        migrations.CreateModel(name='Teacher', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=200)), ('email', models.EmailField(blank=True, max_length=254)), ('is_active', models.BooleanField(default=True)), ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='api.department'))]),
        migrations.CreateModel(name='ProspectusEntry', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('semester', models.PositiveIntegerField()), ('course_code', models.CharField(max_length=50)), ('course_title', models.CharField(blank=True, max_length=250)), ('credit_hours', models.PositiveIntegerField(default=3)), ('course_type', models.CharField(choices=[('theory','Theory'),('lab','Laboratory')], default='theory', max_length=10)), ('is_elective', models.BooleanField(default=False)), ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospectus_entries', to='api.program'))], options={'unique_together': {('program', 'semester', 'course_code')}}),
        migrations.CreateModel(name='Course', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('code', models.CharField(max_length=50)), ('title', models.CharField(max_length=250)), ('credit_hours', models.PositiveIntegerField(default=3)), ('course_type', models.CharField(choices=[('theory','Theory'),('lab','Laboratory')], default='theory', max_length=10)), ('is_elective', models.BooleanField(default=False)), ('upload_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.uploadsession'))], options={'unique_together': {('upload_session', 'code')}}),
        migrations.CreateModel(name='Section', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('year', models.PositiveIntegerField(default=1)), ('semester', models.PositiveIntegerField(default=1)), ('label', models.CharField(default='A', max_length=20)), ('student_count', models.PositiveIntegerField(default=30)), ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.program'))], options={'unique_together': {('program', 'year', 'label')}}),
        migrations.CreateModel(name='CourseOffering', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('sessions_per_week', models.PositiveIntegerField(default=1)), ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='api.course')), ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='api.section')), ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='api.teacher')), ('upload_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='api.uploadsession'))]),
        migrations.CreateModel(name='TimetableEntry', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('generated_at', models.DateTimeField(auto_now=True)), ('course_code', models.CharField(max_length=50)), ('course_title', models.CharField(max_length=250)), ('teacher_name', models.CharField(max_length=200)), ('section_label', models.CharField(max_length=60)), ('program_code', models.CharField(max_length=20)), ('year', models.PositiveIntegerField()), ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='api.courseoffering')), ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='api.room')), ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='api.timeslot'))], options={'unique_together': {('room', 'time_slot')}}),
        migrations.AddIndex(model_name='teacher', index=models.Index(fields=['name'], name='api_teacher_name_639ce4_idx')),
        migrations.AddIndex(model_name='prospectusentry', index=models.Index(fields=['course_code'], name='api_prospec_course__253f51_idx')),
        migrations.AddIndex(model_name='course', index=models.Index(fields=['code'], name='api_course_code_957a41_idx')),
        migrations.AddIndex(model_name='timetableentry', index=models.Index(fields=['program_code', 'year'], name='api_timeta_program_653b14_idx')),
        migrations.AddIndex(model_name='timetableentry', index=models.Index(fields=['teacher_name'], name='api_timeta_teacher_750ab8_idx')),
    ]
