# Generated by Django 6.0.4 on 2026-04-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='course',
            new_name='api_course_code_2921ed_idx',
            old_name='api_course_code_957a41_idx',
        ),
        migrations.RenameIndex(
            model_name='prospectusentry',
            new_name='api_prospec_course__75af50_idx',
            old_name='api_prospec_course__253f51_idx',
        ),
        migrations.RenameIndex(
            model_name='teacher',
            new_name='api_teacher_name_553bfc_idx',
            old_name='api_teacher_name_639ce4_idx',
        ),
        migrations.RenameIndex(
            model_name='timetableentry',
            new_name='api_timetab_program_1456b4_idx',
            old_name='api_timeta_program_653b14_idx',
        ),
        migrations.RenameIndex(
            model_name='timetableentry',
            new_name='api_timetab_teacher_ef4148_idx',
            old_name='api_timeta_teacher_750ab8_idx',
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['teacher_name', 'time_slot'], name='api_timetab_teacher_deef45_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['section_label', 'time_slot'], name='api_timetab_section_03f77d_idx'),
        ),
    ]
